const $=id=>document.getElementById(id);let image=null,busy=false,lastGarment=null,lastEvents='',lastResults='',dirtyImage=false;
async function request(path,body){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-App-Token':window.APP_TOKEN},body:JSON.stringify(body)});const s=await r.json();if(!r.ok)throw Error(s.error);render(s);return s}
function showError(e){$('error').hidden=false;$('error').textContent=e.message||String(e)}
function file(f){if(!f)return;if(busy)return showError(Error('Stop the active run before changing the image.'));if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5000000)return showError(Error('Use a JPEG, PNG or WebP smaller than 5 MB.'));const reader=new FileReader();reader.onload=()=>{image=reader.result;dirtyImage=true;$('preview').src=image;$('preview').hidden=false;$('drop-copy').hidden=true;$('analyze').disabled=false;$('description').hidden=true;$('error').hidden=true;lastGarment=null};reader.readAsDataURL(f)}
$('photo').onchange=e=>file(e.target.files[0]);for(const t of ['dragenter','dragover'])$('drop').addEventListener(t,e=>{e.preventDefault();$('drop').classList.add('drag')});$('drop').addEventListener('dragleave',()=>$('drop').classList.remove('drag'));$('drop').addEventListener('drop',e=>{e.preventDefault();$('drop').classList.remove('drag');file(e.dataTransfer.files[0])});
$('analyze').onclick=async()=>{try{busy=true;$('analyze').disabled=true;await request('analyze',{image});dirtyImage=false}catch(e){busy=false;$('analyze').disabled=false;showError(e)}};
$('search').onclick=async()=>{try{busy=true;$('search').disabled=true;await request('search',{query:$('query').value,sources:[...document.querySelectorAll('[name=shop]:checked')].map(x=>x.value)})}catch(e){busy=false;$('search').disabled=false;showError(e)}};
$('stop').onclick=()=>request('stop',{}).catch(showError);
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function safeUrl(s){try{return new URL(s).protocol==='https:'?s:null}catch{return null}}
function render(s){busy=['analyzing','searching','ranking','verifying','stopping'].includes(s.status);$('photo').disabled=busy;$('analyze').disabled=busy||!image;$('search').disabled=busy||!s.garment||dirtyImage;$('stop').hidden=!busy;$('stop').disabled=s.status==='stopping';$('run-status').textContent=({analyzing:'Reading your image…',searching:'Browsing the shops…',ranking:'Comparing products…',verifying:'Checking product pages…',ready:'Ready to search',complete:'Search finished',stopped:'Stopped',stopping:'Finishing the current request…',error:'Needs attention'})[s.status]||'Ready when you are';$('connection').textContent=s.configuration.nebius&&s.configuration.jev?'Nebius + Jev configured':'Setup needed: '+[!s.configuration.nebius?'Nebius key':'',!s.configuration.jev?'TypeSafe key':''].filter(Boolean).join(', ');
if(s.error)showError(Error(s.error));else $('error').hidden=true;
if(!dirtyImage&&s.garment&&JSON.stringify(s.garment)!==lastGarment){lastGarment=JSON.stringify(s.garment);$('description').hidden=false;$('garment').textContent=s.garment.description;$('query').value=s.garment.search_query;$('attributes').replaceChildren(...[s.garment.category,s.garment.color,s.garment.pattern,s.garment.silhouette].filter(x=>x&&x!=='unknown').map(t=>el('span',t)));$('uncertainty').textContent=s.garment.uncertainty.length?'Uncertain: '+s.garment.uncertainty.join(' '):''}
if(s.screenshot){$('screen').src='data:image/jpeg;base64,'+s.screenshot;$('screen').hidden=false;$('screen-empty').hidden=true}else{$('screen').hidden=true;$('screen-empty').hidden=false}$('url').textContent=s.page_url||'Dedicated shopping browser';$('source-status').replaceChildren(...Object.values(s.sources).map(x=>{const a=el('span',x.name+' · '+x.status);a.title=x.message||'';return a}));
const es=JSON.stringify(s.events);if(es!==lastEvents&&s.events.length){lastEvents=es;$('events').replaceChildren(...[...s.events].reverse().map(x=>{const li=el('li',x.message);li.append(el('small',[new Date(x.at*1000).toLocaleTimeString(),x.model,x.latency_ms!==undefined?(x.latency_ms/1000).toFixed(2)+'s model call':''].filter(Boolean).join(' · ')));return li}))}
const rs=JSON.stringify([s.results,s.status]);if(rs!==lastResults){lastResults=rs;$('result-count').textContent=s.results.length?s.results.length+' possible matches':'No products yet';if(!s.results.length){const a=el('div',s.status==='complete'?'No verified product matches collected.':'The details make the difference.','no-results');a.append(el('span',s.status==='complete'?'Check the source statuses above. Try a simpler phrase or another shop.':'Relevant products and their original links will land here as the search runs.'));$('results').replaceChildren(a)}else $('results').replaceChildren(...s.results.map(r=>{const a=el('article',undefined,'product');if(safeUrl(r.image)){const img=el('img');img.src=r.image;img.alt=r.title;img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>img.replaceWith(el('div','Image unavailable','no-photo'));a.append(img)}else a.append(el('div','No product image observed','no-photo'));a.append(el('p',r.source,'source'));const h=el('h3'),link=el('a',r.title);link.href=safeUrl(r.url)||'#';link.target='_blank';link.rel='noopener noreferrer';h.append(link);a.append(h,el('span',r.price||'Price not shown','price'),el('span',r.match==='strong'?'Strong text match':'Possible match','match'));const v=r.verification||{status:'card_only',reason:'Only search-card evidence available.'};a.append(el('p',({page_checked:'✓ Product page checked',title_changed:'✓ Product ID checked · title updated',card_only:'Card evidence only',blocked:'Page check blocked',unverified:'Page check incomplete'})[v.status]||'Not verified','verification'));const d=el('details');d.append(el('summary','Observed product details'),el('p',v.reason),el('p',r.evidence),el('p',r.page_price?'Price observed on product page':'Price from search card; not confirmed on product page'),el('p','Observed '+new Date(r.observed_at).toLocaleString()));a.append(d);return a}))}}
async function poll(){try{const r=await fetch('/api/state');if(!r.ok)throw Error('Cannot reach the local server');render(await r.json())}catch(e){$('connection').textContent='Local server disconnected'}finally{setTimeout(poll,900)}}poll();
